export const SECRET_KEY = '@APP_MOBILE';
export const ASYNC_STORAGE_KEY_IS_LOGIN = 'IS_LOGIN';
export const ASYNC_STORAGE_KEY_USER_INFO = 'USER_INFO';
export const ASYNC_STORAGE_KEY_USERNAME_LOGIN = 'USER_LOGIN';
